force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Job application records</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Annual_Salary__c.field-meta.xml
<CustomField>
    <fullName>Annual_Salary__c</fullName>
    <formula>Desired_Salary__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Annual Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>Current status of application</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Federal_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Federal_Tax_Amount__c</fullName>
    <label>Federal Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Application.cls
/**
 * Application class
 */
public with sharing class Application {
    /**
     * This method assigns the applicable tax to each tax field by calling out the helper method that calculates each tax
     * @param applications List of new or updated application records
     */
    public static void populateFederalTax(List<Application__c> applications) {
        if (!applications.isEmpty()) {
           for (Application__c app : applications) {
            app.Federal_Tax_Amount__c = ApplicationHelper.calculateFederalTax(app.Annual_Salary__c);
            app.Medicare_Withholding__c = ApplicationHelper.calculateMedicareTax(app.Annual_Salary__c);
            app.Social_Security__c = ApplicationHelper.calculateSocialSecurityTax(app.Annual_Salary__c);
            }
        }
    }
    /**
     * This method inserts tasks based on the task status of Application records
     * @param newApps list of new applications
     * @param oldAppMap list of old values in list of applications
     */
    public static void createTasksOnChangeStatus(List<Application__c> newApps, Map<Id, Application__c> oldAppMap) {
        if(!newApps.isEmpty()){
            List<Task> tasksToCreate = new List<Task>();

            for (Application__c app : newApps) {
                Application__c oldApp = oldAppMap.get(app.Id);
                if (app.Application_Status__c != oldApp.Application_Status__c) {
                    List<Task> newTasks = ApplicationHelper.createTasksForStatus(app);
                    tasksToCreate.addAll(newTasks);
                }
            }
            if (!tasksToCreate.isEmpty()) {
                Database.insert(tasksToCreate, AccessLevel.USER_MODE);
            }
        }
    }
}