force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Job application records</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>Current status of application</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Follow__c.field-meta.xml
<CustomField>
    <fullName>Follow__c</fullName>
    <description>Date to follow up after application submitted</description>
    <inlineHelpText>Date to follow up after application submitted</inlineHelpText>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ScheduleApplicationCleanUp.cls
/**
 * Moves the record status to closed and dpdate the notes field that the job application was closed by an automated process. Stale Criteria:
 * Status is not Closed or Accepted
 * Follow Date 30 days old or more
 */
public with sharing class ScheduleApplicationCleanUp implements Schedulable {
    public void execute (SchedulableContext sc) {
        List<Application__c> applications = [SELECT Id, Application_Status__c, Follow__c
                                             FROM Application__c
                                             WHERE Application_Status__c NOT IN ('Closed', 'Accepted') AND Follow__c <= :Date.today().addDays(-30)];

        if (!applications.isEmpty()) {
            for (Application__c app : applications) {
                app.Application_Status__c = 'Closed';
                app.Notes__c = 'This job application was closed by an automated process';
            }
        }
        update applications;
    }
}
    /*
    // get set of Application Id to run list of open tasks to close
        Set<Id> applicationId = new Set<Id>();
        List<Task> tasksToClose = [SELECT Id, Status, WhatId 
                                   FROM Task 
                                   WHERE WhatId IN :applicationId
                                   AND Status != 'Completed'];
    */