force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Job application records</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <description>Applicant</description>
    <label>Applicant</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact Type should be an Applicant</errorMessage>
        <filterItems>
            <field>Contact.Contact_Type__c</field>
            <operation>equals</operation>
            <value>Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>Current status of application</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Company</description>
    <formula>Job_Number__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Follow__c.field-meta.xml
<CustomField>
    <fullName>Follow__c</fullName>
    <description>Date to follow up after application submitted</description>
    <inlineHelpText>Date to follow up after application submitted</inlineHelpText>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Application for which Job Number</description>
    <label>Job Number</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>Holds job records</description>
    <label>Job</label>
    <nameField>
        <displayFormat>Job-{0000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Where is this job source from for the Hiring Company</description>
    <label>Primary Account Source</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <description>Job Description</description>
    <label>Job Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Rate__c/Tax_Rate__c.object-meta.xml
<CustomObject>
    <description>Used to track tax rates</description>
    <label>Tax Rate</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tax Rate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Rate__c/fields/Additional_Medicare_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Additional_Medicare_Tax_Rate__c</fullName>
    <description>Additional tax on top of regular Medicare tax, only on wages above the threshold</description>
    <label>Additional Medicare Tax Rate</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tax_Rate__c/fields/Bracket_Max__c.field-meta.xml
<CustomField>
    <fullName>Bracket_Max__c</fullName>
    <description>Maximum Salary for Tax Bracket</description>
    <label>Bracket Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Rate__c/fields/Bracket_Min__c.field-meta.xml
<CustomField>
    <fullName>Bracket_Min__c</fullName>
    <description>Minimum Salary for Tax Bracket</description>
    <label>Bracket Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Rate__c/fields/Medicare_Threshold_Amount__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Threshold_Amount__c</fullName>
    <description>Enter Filing Year Additional Medicare Tax Threshold Amount</description>
    <label>Medicare Threshold Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Rate__c/fields/Social_Security_Wage_Limit__c.field-meta.xml
<CustomField>
    <fullName>Social_Security_Wage_Limit__c</fullName>
    <label>Social Security Wage Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Rate__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tax_Rate__c/fields/Tax_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Type__c</fullName>
    <description>Tax Rate for which deduction</description>
    <label>Tax Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Social Security</fullName>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleApplicationCleanUpTest.cls
@IsTest
public with sharing class ScheduleApplicationCleanUpTest {
    @TestSetup
    static void setupTestData(){
        List<Tax_Rate__C> taxRates = new List<Tax_Rate__c>();
        taxRates.add(new Tax_Rate__c(Tax_Rate_Type__c = 'Federal', Bracket_Min__c = 0, Bracket_Max__c = 11925, Tax_Rate__c = 10));
        taxRates.add(new Tax_Rate__c(Tax_Rate_Type__c = 'Federal', Bracket_Min__c = 11926, Bracket_Max__c = 48475, Tax_Rate__c = 12));
        taxRates.add(new Tax_Rate__c(Tax_Rate_Type__c = 'Federal', Bracket_Min__c = 48476, Bracket_Max__c = 103350, Tax_Rate__c = 22));
        taxRates.add(new Tax_Rate__c(Tax_Rate_Type__c = 'Federal', Bracket_Min__c = 103351, Bracket_Max__c = 197300, Tax_Rate__c = 24));
        taxRates.add(new Tax_Rate__c(Tax_Rate_Type__c = 'Federal', Bracket_Min__c = 197301, Bracket_Max__c = 250525, Tax_Rate__c = 32));
        taxRates.add(new Tax_Rate__c(Tax_Rate_Type__c = 'Federal', Bracket_Min__c = 250526, Bracket_Max__c = 626350, Tax_Rate__c = 35));
        taxRates.add(new Tax_Rate__c(Tax_Rate_Type__c = 'Federal', Bracket_Min__c = 626351, Bracket_Max__c = 999999, Tax_Rate__c = 37));
        taxRates.add(new Tax_Rate__c(Tax_Rate_Type__c = 'Medicare', Medicare_Threshold_Amount__c = 200000, Additional_Medicare_Tax_Rate__c = .90, Tax_Rate__c = 1.45));
        taxRates.add(new Tax_Rate__c(Tax_Rate_Type__c = 'Social Security', Social_Security_Wage_Limit__c = 176100, Tax_Rate__c = 6.2));
        insert taxRates;

        Account newAcc = new Account (Name = 'Jacks Consulting Firm');
        insert newAcc;

        Contact newCont = new Contact (LastName = 'Snuggles', Level__c = 'Primary', AccountId = newAcc.Id);
        insert newCont;

        Job__c newJob = new Job__c(Job_Description__c = 'Salesforce Developer II', Company__c = newAcc.Id);
        Job__c newJob1 = new Job__c(Job_Description__c = 'Salesforce Developer II', Company__c = newAcc.Id);
        Job__c newJob2 = new Job__c(Job_Description__c = 'Salesforce Developer II', Company__c = newAcc.Id);
        List<Job__c> jobsToInsert = new List<Job__c>{newJob, newJob1, newJob2};
        insert jobsToInsert;

        Contact newAppCont = new Contact (LastName = 'Bloom', RecordTypeId = '012fj000003jOMDAA2');
        Contact newAppCont1 = new Contact (LastName = 'Flora', RecordTypeId = '012fj000003jOMDAA2');
        Contact newAppCont2 = new Contact (LastName = 'Stella', RecordTypeId = '012fj000003jOMDAA2');
        Contact newAppCont3 = new Contact (LastName = 'Musa', RecordTypeId = '012fj000003jOMDAA2');
        List<Contact> contToInsert = new List<Contact>{newAppCont, newAppCont1, newAppCont2, newAppCont3};
        insert contToInsert;

        Application__c newApp = new Application__c (Applicant__c = newAppCont.Id, Job_Number__c = newJob.Id, Application_Status__c = 'Saved', Follow__c = Date.today().addDays(-32));
        Application__c newApp1 = new Application__c (Applicant__c = newAppCont3.Id, Job_Number__c = newJob2.Id, Application_Status__c = 'Applying', Follow__c = Date.today().addDays(-30));
        Application__c newApp2 = new Application__c (Applicant__c = newAppCont1.Id, Job_Number__c = newJob1.Id, Application_Status__c = 'Accepted', Follow__c = Date.today().addDays(-32));// this one should not update
        Application__c newApp3 = new Application__c(Applicant__c = newAppCont2.Id, Job_Number__c = newJob2.Id, Application_Status__c = '', Follow__c = Date.today().addDays(-45));
        Application__c newApp4 = new Application__c(Applicant__c = newAppCont3.Id, Job_Number__c = newJob1.Id, Application_Status__c = '', Follow__c = Date.today().addDays(-12));// this one should not update
        Application__c newApp5 = new Application__c(Applicant__c = newAppCont.Id, Job_Number__c = newJob1.Id, Application_Status__c = 'Interviewing', Follow__c = Date.today().addDays(-12));// this one should not update
        Application__c newApp6 = new Application__c(Applicant__c = newAppCont2.Id, Job_Number__c = newJob.Id, Application_Status__c = 'Negotiating', Follow__c = Date.today().addDays(-42));
        Application__c newApp7 = new Application__c(Applicant__c = newAppCont3.Id, Job_Number__c = newJob.Id, Application_Status__c = 'Closed', Follow__c = Date.today().addDays(-42));// this one should not update
        List<Application__c> appsToInsert = new List<Application__c>{newApp,newApp1,newApp2, newApp3, newApp4, newApp5, newApp6, newApp7};
        insert appsToInsert;
    }

    @IsTest
    public static void ScheduleApplicationCleanUpTest_Pos() {

        List<Application__c> apps = [SELECT Id, Application_Status__c 
                                      FROM Application__c];

        Test.startTest();
            ScheduleApplicationCleanUp schedulable = new ScheduleApplicationCleanUp();
            schedulable.execute(null);
        Test.stopTest();

        List<Application__c> processedApps = [SELECT Id, Notes__c, Application_Status__c
                                              FROM Application__c
                                              WHERE Application_Status__c = 'Closed'];
        
        System.assertEquals(5, processedApps.size(), 'There should have been 5 applications closed via the scheduled process');
    }
}